# -*- coding: utf-8 -*-
"""discord_bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q2inX5QWH0wXrguO9i7JQAT-ngw9mQMs
"""

!pip install -q discord.py sentence-transformers pandas scikit-learn

import discord
import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


# ใส่ Discord Bot Token ของตัวเองตรงนี้

DISCORD_TOKEN = "ใส่ Discord Bot Token ของตัวเองตรงนี้"
if DISCORD_TOKEN == "ใส่ Discord Bot Token ของตัวเองตรงนี้":
    raise ValueError("กรุณาใส่ Discord Bot Token ของตัวเองก่อนรันบอท")

from google.colab import drive
drive.mount('/content/drive')

main_dataset_path = "/content/drive/MyDrive/AI_Builder/thai_gaming_toxic_dataset_v2_simple.csv"

df = pd.read_csv(main_dataset_path)

df = df.dropna(subset=["text", "label"]).copy()
df["text"] = df["text"].astype(str).str.strip()
df["label"] = df["label"].astype(str).str.strip()

print("Total rows:", len(df))
print(df["label"].value_counts())

X_train_text, X_test_text, y_train, y_test = train_test_split(
    df["text"],
    df["label"],
    test_size=0.3,
    random_state=42,
    stratify=df["label"]
)

print("Loading MiniLM embedding model...")
embedder = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

print("Encoding training data...")
X_train_emb = embedder.encode(
    list(X_train_text),
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Training KNN13...")
knn13_model = KNeighborsClassifier(
    n_neighbors=13,
    metric="cosine"
)

knn13_model.fit(X_train_emb, y_train)

print("Model ready.")

from datetime import timedelta

intents = discord.Intents.default()
intents.message_content = True

client = discord.Client(intents=intents)


def predict_toxicity(text):
    text_emb = embedder.encode(
        [text],
        convert_to_numpy=True
    )

    prediction = knn13_model.predict(text_emb)[0]
    probability = knn13_model.predict_proba(text_emb)[0]

    class_names = knn13_model.classes_

    prob_dict = {
        class_names[i]: float(probability[i])
        for i in range(len(class_names))
    }

    normal_prob = prob_dict.get("Normal", 0)
    toxic_prob = prob_dict.get("Toxic", 0)

    return prediction, normal_prob, toxic_prob


@client.event
async def on_ready():
    print(f"Logged in as {client.user}")
    print("Bot is ready and listening to messages.")


@client.event
async def on_message(message):
    print("on_message triggered")

    if message.author.bot:
        print("Ignored bot message")
        return

    text = message.content.strip()

    print("Author:", message.author)
    print("Channel:", message.channel)
    print("Message:", text)

    if text == "":
        print("Empty message")
        return

    prediction, normal_prob, toxic_prob = predict_toxicity(text)

    print("Prediction:", prediction)
    print("Normal:", normal_prob)
    print("Toxic:", toxic_prob)

    await message.channel.send(
        f"🔎 Checked: **{prediction}**\n"
        f"Normal: `{normal_prob:.2%}` | Toxic: `{toxic_prob:.2%}`"
    )

    if prediction == "Toxic":
        try:
            await message.author.timeout(
                timedelta(seconds=5),
                reason="Detected toxic message by Thai Gaming Toxic Detector"
            )

            await message.channel.send(
                f"🚨 {message.author.mention} ถูก timeout 5 วินาที"
            )

        except discord.Forbidden:
            await message.channel.send(
                "⚠️ Toxic แต่ timeout ไม่ได้: บอทไม่มีสิทธิ์ Moderate Members หรือ role ต่ำกว่าคนนี้"
            )

        except discord.HTTPException as e:
            await message.channel.send(
                f"⚠️ Timeout ไม่สำเร็จ: `{e}`"
            )

!pip install -q nest_asyncio

import nest_asyncio
nest_asyncio.apply()

print("Starting Discord bot...")

await client.start(os.environ["DISCORD_TOKEN"])