# -*- coding: utf-8 -*-
"""thai_gaming_toxicity_detector_all_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ofM-fkTREDuUd7Hw9W-Og1xOR-1Y2zC
"""

!pip install -q sentence-transformers

from google.colab import drive
drive.mount('/content/drive')

import os
import random
import numpy as np
import pandas as pd
import tensorflow as tf
from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

file_path = "/content/drive/MyDrive/AI_Builder/thai_gaming_toxic_dataset_v2_simple.csv"

df = pd.read_csv(file_path)

df.head()

df = df.dropna(subset=["text", "label"]).copy()

df["text"] = df["text"].astype(str).str.strip()
df["label"] = df["label"].astype(str).str.strip()

texts = df["text"].tolist()
labels = df["label"].tolist()

print("Total rows:", len(df))
print(df["label"].value_counts())
print("Duplicates:", df.duplicated(subset=["text", "label"]).sum())
print("len(texts):", len(texts))
print("len(labels):", len(labels))

df.head()

X_train_text, X_test_text, y_train, y_test = train_test_split(
    texts,
    labels,
    test_size=0.3,
    random_state=42,
    stratify=labels
)

print("Train size:", len(X_train_text))
print("Test size:", len(X_test_text))

vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5)
)

X_train = vectorizer.fit_transform(X_train_text)
X_test = vectorizer.transform(X_test_text)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

unseen_path = "/content/drive/MyDrive/AI_Builder/thai_gaming_toxic_unseen_test_clean_244.csv"

unseen_df = pd.read_csv(unseen_path)

unseen_df = unseen_df.dropna(subset=["text", "label"]).copy()
unseen_df["text"] = unseen_df["text"].astype(str).str.strip()
unseen_df["label"] = unseen_df["label"].astype(str).str.strip()

unseen_texts = unseen_df["text"].tolist()
unseen_labels = unseen_df["label"].tolist()

print("Clean unseen rows:", len(unseen_df))
print(unseen_df["label"].value_counts())

main_text_set = set(df["text"].astype(str).str.strip())
unseen_text_set = set(unseen_df["text"].astype(str).str.strip())

overlap_texts = main_text_set.intersection(unseen_text_set)

print("Overlap with main dataset:", len(overlap_texts))

unseen_df.head()

toxic_keywords = [
    "กาก", "โง่", "ควาย", "ขยะ", "ปัญญาอ่อน",
    "แจก", "ภาระ", "ห่วย", "ตาย", "ทีมพัง",
    "เล่นไม่เป็น", "ถ่วงทีม", "ไม่มีสมอง"
]

def keyword_blacklist_predict(text):
    text = str(text)
    for word in toxic_keywords:
        if word in text:
            return "Toxic"
    return "Normal"

keyword_pred = [keyword_blacklist_predict(text) for text in unseen_texts]

tfidf_log_model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"
)

tfidf_log_model.fit(X_train, y_train)

tfidf_svm_model = LinearSVC(
    class_weight="balanced",
    max_iter=5000
)

tfidf_svm_model.fit(X_train, y_train)

emb_log_model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"
)

unseen_dataset_path = "/content/drive/MyDrive/AI_Builder/thai_gaming_toxic_unseen_test_clean_244.csv"

unseen_df = pd.read_csv(unseen_dataset_path)

unseen_df = unseen_df.dropna(subset=["text", "label"]).copy()
unseen_df["text"] = unseen_df["text"].astype(str).str.strip()
unseen_df["label"] = unseen_df["label"].astype(str).str.strip()

unseen_texts = unseen_df["text"].tolist()
unseen_labels = unseen_df["label"].tolist()

print("Total rows:", len(unseen_df))
print(unseen_df["label"].value_counts())

embedder = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

X_train_emb = embedder.encode(
    X_train_text,
    show_progress_bar=True,
    convert_to_numpy=True
)

X_test_emb = embedder.encode(
    X_test_text,
    show_progress_bar=True,
    convert_to_numpy=True
)

X_unseen_emb = embedder.encode(
    unseen_texts,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("X_train_emb shape:", X_train_emb.shape)
print("X_test_emb shape:", X_test_emb.shape)
print("X_unseen_emb shape:", X_unseen_emb.shape)

tfidf_log_model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"
)

tfidf_log_model.fit(X_train, y_train)

tfidf_svm_model = LinearSVC(
    class_weight="balanced",
    max_iter=5000
)

tfidf_svm_model.fit(X_train, y_train)

emb_log_model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"
)

emb_log_model.fit(X_train_emb, y_train)

emb_svm_model = LinearSVC(
    class_weight="balanced",
    max_iter=5000
)

emb_svm_model.fit(X_train_emb, y_train)

emb_rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

emb_rf_model.fit(X_train_emb, y_train)

knn5_model = KNeighborsClassifier(
    n_neighbors=5,
    metric="cosine"
)

knn5_model.fit(X_train_emb, y_train)

knn9_model = KNeighborsClassifier(
    n_neighbors=9,
    metric="cosine"
)

knn9_model.fit(X_train_emb, y_train)

knn13_model = KNeighborsClassifier(
    n_neighbors=13,
    metric="cosine"
)

knn13_model.fit(X_train_emb, y_train)

X_unseen = vectorizer.transform(unseen_texts)

tfidf_log_pred = tfidf_log_model.predict(X_unseen)
tfidf_svm_pred = tfidf_svm_model.predict(X_unseen)

emb_log_pred = emb_log_model.predict(X_unseen_emb)
emb_svm_pred = emb_svm_model.predict(X_unseen_emb)
emb_rf_pred = emb_rf_model.predict(X_unseen_emb)

knn5_pred = knn5_model.predict(X_unseen_emb)
knn9_pred = knn9_model.predict(X_unseen_emb)
knn13_pred = knn13_model.predict(X_unseen_emb)

print("=== Method 1: Keyword / Blacklist basic baseline ===")
print("Accuracy:", accuracy_score(unseen_labels, keyword_pred))
print(classification_report(unseen_labels, keyword_pred))

print("=== Method 2: TF-IDF + Logistic Regression ===")
print("Accuracy:", accuracy_score(unseen_labels, tfidf_log_pred))
print(classification_report(unseen_labels, tfidf_log_pred))

print("=== Method 3: TF-IDF + Linear SVM ===")
print("Accuracy:", accuracy_score(unseen_labels, tfidf_svm_pred))
print(classification_report(unseen_labels, tfidf_svm_pred))

print("=== Method 4: Sentence Embedding MiniLM + Logistic Regression ===")
print("Accuracy:", accuracy_score(unseen_labels, emb_log_pred))
print(classification_report(unseen_labels, emb_log_pred))

print("=== Method 5: Sentence Embedding MiniLM + Linear SVM ===")
print("Accuracy:", accuracy_score(unseen_labels, emb_svm_pred))
print(classification_report(unseen_labels, emb_svm_pred))

print("=== Method 6: Sentence Embedding MiniLM + Random Forest ===")
print("Accuracy:", accuracy_score(unseen_labels, emb_rf_pred))
print(classification_report(unseen_labels, emb_rf_pred))

SEED = 21

os.environ["PYTHONHASHSEED"] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

tf.keras.backend.clear_session()

le = LabelEncoder()

y_train_num = le.fit_transform(y_train)

X_train_emb_float = np.asarray(X_train_emb).astype("float32")
X_unseen_emb_float = np.asarray(X_unseen_emb).astype("float32")

X_dense_train, X_dense_val, y_dense_train, y_dense_val = train_test_split(
    X_train_emb_float,
    y_train_num,
    test_size=0.2,
    random_state=SEED,
    stratify=y_train_num
)

dense_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train_emb_float.shape[1],)),

    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dropout(0.2),

    tf.keras.layers.Dense(1, activation="sigmoid")
])

dense_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = dense_model.fit(
    X_dense_train,
    y_dense_train,
    validation_data=(X_dense_val, y_dense_val),
    epochs=15,
    batch_size=32,
    verbose=1
)

dense_prob = dense_model.predict(X_unseen_emb_float, verbose=0).ravel()

dense_pred_num = (dense_prob >= 0.5).astype(int)

dense_pred = le.inverse_transform(dense_pred_num)

dense_accuracy = accuracy_score(unseen_labels, dense_pred)
dense_macro_f1 = f1_score(unseen_labels, dense_pred, average="macro")

print("=== Method 7: Dense Layer on Sentence Embedding MiniLM + Fixed Seed ===")
print("Accuracy:", accuracy_score(unseen_labels, dense_pred))
print(classification_report(unseen_labels, dense_pred))

print("=== Method 8: Sentence Embedding MiniLM + KNN5 ===")
print("Accuracy:", accuracy_score(unseen_labels, knn5_pred))
print(classification_report(unseen_labels, knn5_pred))

print("=== Method 9: Sentence Embedding MiniLM + KNN9 ===")
print("Accuracy:", accuracy_score(unseen_labels, knn9_pred))
print(classification_report(unseen_labels, knn9_pred))

print("=== Method 10: Sentence Embedding MiniLM + KNN13 ===")
print("Accuracy:", accuracy_score(unseen_labels, knn13_pred))
print(classification_report(unseen_labels, knn13_pred))

from sklearn.metrics import accuracy_score, f1_score
import pandas as pd

def get_result(model_name, y_pred):
    return {
        "method": model_name,
        "accuracy": accuracy_score(unseen_labels, y_pred),
        "accuracy_percent": round(accuracy_score(unseen_labels, y_pred) * 100, 2),
        "macro_f1": round(f1_score(unseen_labels, y_pred, average="macro"), 4)
    }

final_results_ordered_df = pd.DataFrame([
    get_result("Method 1: Keyword / Blacklist basic baseline", keyword_pred),
    get_result("Method 2: TF-IDF + Logistic Regression", tfidf_log_pred),
    get_result("Method 3: TF-IDF + Linear SVM", tfidf_svm_pred),
    get_result("Method 4: Sentence Embedding MiniLM + Logistic Regression", emb_log_pred),
    get_result("Method 5: Sentence Embedding MiniLM + Linear SVM", emb_svm_pred),
    get_result("Method 6: Sentence Embedding MiniLM + Random Forest", emb_rf_pred),
    get_result("Method 7: Dense Layer + Fixed Seed", dense_pred),
    get_result("Method 8: Sentence Embedding MiniLM + KNN5", knn5_pred),
    get_result("Method 9: Sentence Embedding MiniLM + KNN9", knn9_pred),
    get_result("Method 10: Sentence Embedding MiniLM + KNN13", knn13_pred)
])

final_results_ordered_df