# -*- coding: utf-8 -*-
"""thai_gaming_toxicity_detector_final_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t13KV30ZaHz0fp0AYZj1DDm8I7XMOCNN
"""

!pip install -q sentence-transformers

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, f1_score

file_path = "/content/drive/MyDrive/AI_Builder/thai_gaming_toxic_dataset_v2_simple.csv"

df = pd.read_csv(file_path)

df.head()

df = df.dropna(subset=["text", "label"]).copy()

df["text"] = df["text"].astype(str).str.strip()
df["label"] = df["label"].astype(str).str.strip()

texts = df["text"].tolist()
labels = df["label"].tolist()

print("Total rows:", len(df))
print(df["label"].value_counts())
print("Duplicates:", df.duplicated(subset=["text", "label"]).sum())
print("len(texts):", len(texts))
print("len(labels):", len(labels))

df.head()


unseen_path = "/content/drive/MyDrive/AI_Builder/thai_gaming_toxic_unseen_test_clean_244.csv"

unseen_df = pd.read_csv(unseen_path)

unseen_df = unseen_df.dropna(subset=["text", "label"]).copy()
unseen_df["text"] = unseen_df["text"].astype(str).str.strip()
unseen_df["label"] = unseen_df["label"].astype(str).str.strip()

unseen_texts = unseen_df["text"].tolist()
unseen_labels = unseen_df["label"].tolist()

print("Clean unseen rows:", len(unseen_df))
print(unseen_df["label"].value_counts())

main_text_set = set(df["text"].astype(str).str.strip())
unseen_text_set = set(unseen_df["text"].astype(str).str.strip())

overlap_texts = main_text_set.intersection(unseen_text_set)

print("Overlap with main dataset:", len(overlap_texts))

unseen_df.head()

embedder = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

X_train_emb = embedder.encode(
    list(X_train_text),
    show_progress_bar=True,
    convert_to_numpy=True
)

X_unseen_emb = embedder.encode(
    unseen_texts,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("X_train_emb shape:", X_train_emb.shape)
print("X_unseen_emb shape:", X_unseen_emb.shape)

knn13_model = KNeighborsClassifier(
    n_neighbors=13,
    metric="cosine"
)

knn13_model.fit(X_train_emb, y_train)

knn13_pred = knn13_model.predict(X_unseen_emb)


print("=== Final Model: Sentence Embedding MiniLM + KNN13 ===")
print("Accuracy:", accuracy_score(unseen_labels, knn13_pred))
print(classification_report(unseen_labels, knn13_pred))
